apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spring-app.fullname" . }}-config
data:
  application.properties: |-
    {{- range $key, $value := .Values.applicationProperties }}
      {{ $key}} = {{ $value }}
    {{- end }}